# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/sources_1/bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_processing_system7_0_0/SPW_ZynqSetup_processing_system7_0_0.xci
# IP: The module: 'SPW_ZynqSetup_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.gen/sources_1/bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_processing_system7_0_0/SPW_ZynqSetup_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPW_ZynqSetup_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/sources_1/bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_processing_system7_0_0/SPW_ZynqSetup_processing_system7_0_0.xci
# IP: The module: 'SPW_ZynqSetup_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.gen/sources_1/bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_processing_system7_0_0/SPW_ZynqSetup_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPW_ZynqSetup_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
