# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Xilinx/Projects/UART_Adder/UART_Adder.srcs/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0.xci
# IP: The module: 'UART_Adder_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx/Projects/UART_Adder/UART_Adder.gen/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Adder_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Xilinx/Projects/UART_Adder/UART_Adder.gen/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Adder_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Xilinx/Projects/UART_Adder/UART_Adder.gen/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Adder_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/Xilinx/Projects/UART_Adder/UART_Adder.srcs/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0.xci
# IP: The module: 'UART_Adder_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx/Projects/UART_Adder/UART_Adder.gen/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Adder_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Xilinx/Projects/UART_Adder/UART_Adder.gen/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Adder_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Xilinx/Projects/UART_Adder/UART_Adder.gen/sources_1/bd/UART_Adder/ip/UART_Adder_rst_ps7_0_100M_0/UART_Adder_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_Adder_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
