# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_c_addsub_0_0/Adder_c_addsub_0_0.xci
# IP: The module: 'Adder_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yannick/Vivado/Adder/Adder.gen/sources_1/bd/Adder/ip/Adder_c_addsub_0_0/Adder_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adder_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_c_addsub_0_0/Adder_c_addsub_0_0.xci
# IP: The module: 'Adder_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yannick/Vivado/Adder/Adder.gen/sources_1/bd/Adder/ip/Adder_c_addsub_0_0/Adder_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adder_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
