set_property SRC_FILE_INFO {cfile:F:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_mainclk.xdc rfile:../../../edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_mainclk.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:F:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_pins.xdc rfile:../../../edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_pins.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks virtual_rxclk] 0.500
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks virtual_rxclk]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks SPW_ZynqSetup_i/clk_wiz_0/inst/clk_in1] -min -add_delay -7.900 [get_ports SPW_Dout]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks SPW_ZynqSetup_i/clk_wiz_0/inst/clk_in1] -max -add_delay 1.000 [get_ports SPW_Dout]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks SPW_ZynqSetup_i/clk_wiz_0/inst/clk_in1] -min -add_delay -7.900 [get_ports SPW_Sout]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks SPW_ZynqSetup_i/clk_wiz_0/inst/clk_in1] -max -add_delay 1.000 [get_ports SPW_Sout]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports SPW_Din]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports SPW_Sin]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports SPW_Dout]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports SPW_Sout]
