set_property SRC_FILE_INFO {cfile:F:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_mainclk.xdc rfile:../../../edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_mainclk.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:F:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_pins.xdc rfile:../../../edit_SpaceWire_light_AXI_v0_2.srcs/constrs_1/new/SPW_pins.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter SPW_Din 0.660
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter SPW_Sin 0.660
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property ASYNC_REG true [get_cells {Test_Implementaiton_i/SpaceWire_light_AXI_0/U0/SPW_IF/TXRSTLOGIC/reset_reg_reg[1]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property ASYNC_REG true [get_cells {Test_Implementaiton_i/SpaceWire_light_AXI_0/U0/SPW_IF/TXRSTLOGIC/reset_reg_reg[0]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks SPW_core_clk_Test_Implementaiton_clk_wiz_0_0] -to [get_clocks SPW_Din]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks SPW_core_clk_Test_Implementaiton_clk_wiz_0_0] -to [get_clocks SPW_Sin]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports SPW_Din]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports SPW_Sin]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports SPW_Dout]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports SPW_Sout]
