# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/sources_1/bd/Test_Implementaiton/ip/Test_Implementaiton_xbar_5/Test_Implementaiton_xbar_5.xci
# IP: The module: 'Test_Implementaiton_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.gen/sources_1/bd/Test_Implementaiton/ip/Test_Implementaiton_xbar_5/Test_Implementaiton_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_Implementaiton_xbar_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.srcs/sources_1/bd/Test_Implementaiton/ip/Test_Implementaiton_xbar_5/Test_Implementaiton_xbar_5.xci
# IP: The module: 'Test_Implementaiton_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.gen/sources_1/bd/Test_Implementaiton/ip/Test_Implementaiton_xbar_5/Test_Implementaiton_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_Implementaiton_xbar_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
