# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder_implementation/ip/Adder_implementation_Adder_wrapper_0_0/Adder_implementation_Adder_wrapper_0_0.xci
# IP: The module: 'Adder_implementation_Adder_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/Adder.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder || ORIG_REF_NAME==Adder} -quiet] -quiet

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_c_addsub_0_0/Adder_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_c_addsub_0_0 || ORIG_REF_NAME==Adder_c_addsub_0_0} -quiet] -quiet

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_byte_register_0_1/Adder_byte_register_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_byte_register_0_1 || ORIG_REF_NAME==Adder_byte_register_0_1} -quiet] -quiet

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_byte_register_0_3/Adder_byte_register_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_byte_register_0_3 || ORIG_REF_NAME==Adder_byte_register_0_3} -quiet] -quiet

# XDC: /home/yannick/Vivado/Adder/Adder.gen/sources_1/bd/Adder/Adder_ooc.xdc

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder_implementation/ip/Adder_implementation_Adder_wrapper_0_0/Adder_implementation_Adder_wrapper_0_0.xci
# IP: The module: 'Adder_implementation_Adder_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/Adder.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder || ORIG_REF_NAME==Adder} -quiet] -quiet

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_c_addsub_0_0/Adder_c_addsub_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_c_addsub_0_0 || ORIG_REF_NAME==Adder_c_addsub_0_0} -quiet] -quiet

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_byte_register_0_1/Adder_byte_register_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_byte_register_0_1 || ORIG_REF_NAME==Adder_byte_register_0_1} -quiet] -quiet

# IP: /home/yannick/Vivado/Adder/Adder.srcs/sources_1/bd/Adder/ip/Adder_byte_register_0_3/Adder_byte_register_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_byte_register_0_3 || ORIG_REF_NAME==Adder_byte_register_0_3} -quiet] -quiet

# XDC: /home/yannick/Vivado/Adder/Adder.gen/sources_1/bd/Adder/Adder_ooc.xdc
