# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SPW_mainclk.xdc

# XDC: new/SPW_pins.xdc

# Block Designs: bd/SPW_ZynqSetup/SPW_ZynqSetup.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup || ORIG_REF_NAME==SPW_ZynqSetup} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_SpaceWire_light_AXI_0_0/SPW_ZynqSetup_SpaceWire_light_AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_SpaceWire_light_AXI_0_0 || ORIG_REF_NAME==SPW_ZynqSetup_SpaceWire_light_AXI_0_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_axi_dma_0_0/SPW_ZynqSetup_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_axi_dma_0_0 || ORIG_REF_NAME==SPW_ZynqSetup_axi_dma_0_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_xbar_0/SPW_ZynqSetup_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_xbar_0 || ORIG_REF_NAME==SPW_ZynqSetup_xbar_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_axi_mem_intercon_0/SPW_ZynqSetup_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_axi_mem_intercon_0 || ORIG_REF_NAME==SPW_ZynqSetup_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_processing_system7_0_0/SPW_ZynqSetup_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_processing_system7_0_0 || ORIG_REF_NAME==SPW_ZynqSetup_processing_system7_0_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_xbar_1/SPW_ZynqSetup_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_xbar_1 || ORIG_REF_NAME==SPW_ZynqSetup_xbar_1} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_ps7_0_axi_periph_0/SPW_ZynqSetup_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_ps7_0_axi_periph_0 || ORIG_REF_NAME==SPW_ZynqSetup_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_rst_ps7_0_100M_0/SPW_ZynqSetup_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_rst_ps7_0_100M_0 || ORIG_REF_NAME==SPW_ZynqSetup_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_clk_wiz_0_0/SPW_ZynqSetup_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_clk_wiz_0_0 || ORIG_REF_NAME==SPW_ZynqSetup_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_auto_pc_0/SPW_ZynqSetup_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_auto_pc_0 || ORIG_REF_NAME==SPW_ZynqSetup_auto_pc_0} -quiet] -quiet

# IP: bd/SPW_ZynqSetup/ip/SPW_ZynqSetup_auto_pc_1/SPW_ZynqSetup_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPW_ZynqSetup_auto_pc_1 || ORIG_REF_NAME==SPW_ZynqSetup_auto_pc_1} -quiet] -quiet

# XDC: f:/Xilinx/ZynqProjects/SpaceWire_IPs/SpaceWire_light_AXI/edit_SpaceWire_light_AXI_v0_2.gen/sources_1/bd/SPW_ZynqSetup/SPW_ZynqSetup_ooc.xdc
